gamepad_node:
  ros__parameters:
    maximum_linear_speed: 0.7
    maximum_angular_speed: 6.28

keyboard_node:
  ros__parameters:
    linear_speed: 0.5
    angular_speed: 6.28

motor_controller_node:
  ros__parameters:
    base_turning_speed: 6.28
    imu_topic: "/imu_data"
    commands_topic: "/motor_command"