simulator_camera:
  ros__parameters:
    gazebo_topic: "/simulator_camera"
    ros_topic: "/camera_stream"

simulator_camera_bridge:
  ros__parameters:
    topic: "/simulator_camera"
    ros_message_type: "sensor_msgs/msg/Image"
    gazebo_message_type: "gz.msgs.Image"

simulator_servo:
  ros__parameters:
    ros_action: "/put_servo_to_pos"
    gazebo_topic: "/model/adeept_awr/joint/camera_servo_joint/cmd_vel"

simulator_servo_bridge:
  ros__parameters:
    topic: "/model/adeept_awr/joint/camera_servo_joint/cmd_vel"
    ros_message_type: "std_msgs/msg/Float64"
    gazebo_message_type: "gz.msgs.Double"

simulator_ultrasonic:
  ros__parameters:
    gazebo_topic_name: "/simulator_ultrasonic"
    obstacle_warning_distance: 0.15
    side_obstacle_minimum_detection_distance: 0.3
    side_obstacle_maximum_detection_distance: 0.7
    
simulator_ultrasonic_bridge:
  ros__parameters:
    topic: "/simulator_ultrasonic"
    ros_message_type: "sensor_msgs/msg/LaserScan"
    gazebo_message_type: "ignition.msgs.LaserScan"

simulator_line_tracking:
  ros__parameters:
    gazebo_topic: "/simulator_line_visibility"
    ros_topic: "/line_visibility"
    left_sensor_name: "adeept_awr/base_link/line_tracking_left" #name of the frame
    middle_sensor_name: "adeept_awr/base_link/line_tracking_middle"
    right_sensor_name: "adeept_awr/base_link/line_tracking_right"
    line_detection_threshold: 50 #grayscale value

simulator_line_tracking_bridge:
  ros__parameters:
    topic: "/simulator_line_visibility"
    ros_message_type: "sensor_msgs/msg/Image"
    gazebo_message_type: "gz.msgs.Image"

simulator_lidar:
  ros__parameters:
    gazebo_topic: "/simulator_lidar"
    ros_topic: "/scan"
    frame_id: "lidar"

simulator_lidar_bridge:
  ros__parameters:
    topic: "/simulator_lidar"
    ros_message_type: "sensor_msgs/msg/LaserScan"
    gazebo_message_type: "ignition.msgs.LaserScan"

simulator_imu_bridge:
  ros__parameters:
    topic: "/simulator_imu"
    ros_message_type: "sensor_msgs/msg/Imu"
    gazebo_message_type: "ignition.msgs.IMU"